config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  namespace :admin,:path => "cms" do
    root 'base#index'
    resources :top_brands
    match 'top_brands/set_order' => 'top_brands#set_order', via: [:post]
    resources :categories do
      match 'activate' => 'categories#activate', via: [:get]
    end
    resources :stores do
      match 'activate' => 'stores#activate', via: [:get]
    end
    resources :coupons do
      match 'activate' => 'coupons#activate', via: [:get]
    end
    resources :users do
      match 'activate' => 'users#activate', via: [:get]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/controllers/admin/top_brands_controller.rb
class Admin::TopBrandsController < Admin::BaseController
  def index
    @admin_top_brands = Store.topbrand.order(:sort).all   
  end

  def new
    @admin_top_brand = Store.new  
  end

  def create
    @store = Store.find(params[:store][:name].to_i)
    if @store
      @last_top_brand =  Store.topbrand.order(:sort).last 
      sort = (@last_top_brand.present?) ? @last_top_brand.sort.to_i+1 : 1
      params = {topbrand: true,sort: sort }
      @store.assign_attributes(params)
      @store.save(validate: false)
    end
    redirect_to admin_top_brands_url
  end

  def set_order
    @lists = params[:list]
    stores = []
    @lists.each_with_index  do |list,index|
      stores.push({id:list.to_i, order: index+1})
    end    
    @admin_top_brands = Store.reorder(stores)
    render json: true
  end  

  def destroy    
    @store = Store.find(params[:id])       
    if @store
      stores = []
      params = {topbrand: false,sort: nil }
      @store.assign_attributes(params)
      @store.save(validate: false)
      @stores = Store.topbrand.order(:sort).all
      @stores.each_with_index  do |list,index|
        stores.push({id: list.id, order: index+1})
      end    
      @admin_top_brands = Store.reorder(stores)
    end
    respond_to do |format|
      format.html { redirect_to admin_top_brands_url, notice: 'Top Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

end

app/helpers/admin/top_brands_helper.rb
module Admin::TopBrandsHelper
end

app/views/admin/top_brands/index.html.erb
<p id="notice"><%= notice %></p>

<div class="form-actions">
  <%= link_to 'Back', request.referer , :class => "btn btn-info custom-btn", data: { turbolinks: false } %>
  <%= link_to 'New Top Brand', new_admin_top_brand_path , :class => "btn btn-success custom-btn", data: { turbolinks: false } %>
</div>


<table class="table table-stripped table-hover" width="100%" >
        <thead>
        <tr>
            <th><i class="mdi mdi-pound"></i></th>
            <th>Store</th>
            <th>Order</th>    
            <th>Action</th>                 
        </tr>
        </thead>

    <tbody id="sortable">  <!-- sortable target -->
        <% @admin_top_brands.each do |item| %>
        <tr id="<%= item.id %>">  <!-- Needs id tag on sorting elements -->
            <td><i class="mdi mdi-cursor-move"></i></td>
            <td><%= item.name %></td>
            <td><%= item.sort %></td>
            <td><%=link_to('<i class="mdi mdi-close-circle"></i> '.html_safe, admin_top_brand_path(item), :method => :delete,data: { confirm: 'Are you sure?' }) %></td>
        </tr>
        <% end %>
    </tbody>
</table>


<br>

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

app/views/admin/top_brands/new.html.erb
<h3>New  Top Brand</h3>


<%= simple_form_for([:admin, @admin_top_brand],:url => admin_top_brands_path,validate: true) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, as: :select, collection: Store.where(topbrand: false).all,:input_html => { :class => 'select2' }%>  
  </div>

  <div class="form-actions">
    <%= f.button :submit,:class => "btn btn-success" %>
    <%= link_to 'Back', admin_top_brands_path , :class => "btn btn-info", data: { turbolinks: false } %>
  </div>
  <br>
<% end %>