config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  namespace :admin,:path => "cms" do
    root 'base#index'
    resources :top_brands
    match 'top_brands/set_order' => 'top_brands#set_order', via: [:post]
    resources :categories do
      match 'activate' => 'categories#activate', via: [:get]
    end
    resources :stores do
      match 'activate' => 'stores#activate', via: [:get]
    end
    resources :coupons do
      match 'activate' => 'coupons#activate', via: [:get]
    end
    resources :users do
      match 'activate' => 'users#activate', via: [:get]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/views/shared/_admin_footer.html.erb
<footer class="footer text-center">
        All Rights Reserved by Nice admin. Designed and Developed by
        <a href="http://lovleyoffers.com">lovleyoffers</a>.
    </footer>

app/views/shared/_admin_header.html.erb
<header class="topbar" data-navbarbg="skin6">
    <nav class="navbar top-navbar navbar-expand-md navbar-light">
        <div class="navbar-header" data-logobg="skin5">
            <!-- This is for the sidebar toggle which is visible on mobile only -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)">
                <i class="ti-menu ti-close"></i>
            </a>
              <div class="navbar-brand">
                <a href="index.html" class="logo">
                    <!-- Logo icon -->
                    <b class="logo-icon">
                        <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                        <!-- Dark Logo icon -->
                        <img src="../../assets/images/logo-icon.png" alt="homepage" class="dark-logo" />
                        <!-- Light Logo icon -->
                        <img src="../../assets/images/logo-light-icon.png" alt="homepage" class="light-logo" />
                    </b>
                    <!--End Logo icon -->
                    <!-- Logo text -->
                    <span class="logo-text">
                        <!-- dark Logo text -->
                        <img src="../../assets/images/logo-text.png" alt="homepage" class="dark-logo" />
                        <!-- Light Logo text -->
                        <img src="../../assets/images/logo-light-text.png" class="light-logo" alt="homepage" />
                    </span>
                </a>
            </div>
               <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="ti-more"></i>
            </a>
        </div>
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin6">
             <ul class="navbar-nav float-left mr-auto">
                <li class="nav-item search-box">
                    <a class="nav-link waves-effect waves-dark" href="javascript:void(0)">
                        <div class="d-flex align-items-center">
                            <i class="mdi mdi-magnify font-20 mr-1"></i>
                            <div class="ml-1 d-none d-sm-block">
                                <span>Search</span>
                            </div>
                        </div>
                    </a>
                    <form class="app-search position-absolute">
                        <input type="text" class="form-control" placeholder="Search &amp; enter">
                        <a class="srh-btn">
                            <i class="ti-close"></i>
                        </a>
                    </form>
                </li>
            </ul>
              <ul class="navbar-nav float-right">
                 <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="../../assets/images/users/1.jpg" alt="user" class="rounded-circle" width="31"></a>
                    <div class="dropdown-menu dropdown-menu-right user-dd animated">
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-user m-r-5 m-l-5"></i> My Profile</a>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-wallet m-r-5 m-l-5"></i> My Balance</a>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-email m-r-5 m-l-5"></i> Inbox</a>
                    </div>
                </li>
                 </ul>
        </div>
    </nav>
</header>

app/views/shared/_admin_sidebar.html.erb
<aside class="left-sidebar" data-sidebarbg="skin5">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/cms" aria-expanded="false">
                        <i class="mdi mdi-av-timer"></i>
                        <span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                <li class="sidebar-item <%=(controller.controller_name == 'categories') ? 'selected' : ''%>">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link <%=(controller.controller_name == 'categories') ? 'active' : ''%>" href="<%=admin_categories_path%>" aria-expanded="false" data-turbolinks="false">
                        <i class="mdi mdi-equal-box"></i>
                        <span class="hide-menu">Categories</span>
                    </a>
                </li>
                
                <li class="sidebar-item <%=(controller.controller_name == 'stores') ? 'selected' : ''%>">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link <%=(controller.controller_name == 'stores') ? 'active' : ''%>" href="<%=admin_stores_path%>" aria-expanded="false" data-turbolinks="false">
                        <i class="mdi mdi-home-map-marker"></i>
                        <span class="hide-menu">Stores</span>
                    </a>
                </li>

                <li class="sidebar-item <%=(controller.controller_name == 'coupons') ? 'selected' : ''%>">
                        <a class="sidebar-link waves-effect waves-dark sidebar-link <%=(controller.controller_name == 'coupons') ? 'active' : ''%>" href="<%=admin_coupons_path%>" aria-expanded="false" data-turbolinks="false">
                            <i class="mdi mdi-shopping"></i>
                            <span class="hide-menu">Coupons</span>
                        </a>
                    </li>

                    <li class="sidebar-item <%=(controller.controller_name == 'coupons') ? 'selected' : ''%>">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link <%=(controller.controller_name == 'users') ? 'active' : ''%>" href="<%=admin_users_path%>" aria-expanded="false" data-turbolinks="false">
                                <i class="mdi mdi-account-multiple"></i>
                                <span class="hide-menu">Users</span>
                            </a>
                        </li>

                        <li class="sidebar-item <%=(controller.controller_name == 'coupons') ? 'selected' : ''%>">
                                <a class="sidebar-link waves-effect waves-dark sidebar-link <%=(controller.controller_name == 'top_brands') ? 'active' : ''%>" href="<%=admin_top_brands_path%>" aria-expanded="false" data-turbolinks="false">
                                    <i class="mdi mdi-star"></i>
                                    <span class="hide-menu">TopBrands</span>
                                </a>
                            </li>


               
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>