config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  namespace :admin,:path => "cms" do
    root 'base#index'
    resources :top_brands
    match 'top_brands/set_order' => 'top_brands#set_order', via: [:post]
    resources :categories do
      match 'activate' => 'categories#activate', via: [:get]
    end
    resources :stores do
      match 'activate' => 'stores#activate', via: [:get]
    end
    resources :coupons do
      match 'activate' => 'coupons#activate', via: [:get]
    end
    resources :users do
      match 'activate' => 'users#activate', via: [:get]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :stores
    validates_presence_of :name,:description
    validates_uniqueness_of :name
    has_one_attached :image    
    attr_accessor :preview
    validates :image, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg'], unless: :preview
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_admin_category, only: [:show, :edit, :update, :destroy]

  # GET /admin/categories
  # GET /admin/categories.json
  def index
    # @admin_categories = Category.all
    
    respond_to do |format|
      format.html
      format.json { render json: CategoryDatatable.new(params,  view_context: view_context) }
    end

  end

  # GET /admin/categories/1
  # GET /admin/categories/1.json
  def show
  end

  # GET /admin/categories/new
  def new
    @admin_category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories
  # POST /admin/categories.json
  def create
    @admin_category = Category.new(admin_category_params)

    respond_to do |format|
      if @admin_category.save
        #  @admin_category.image.attach(params[:image])
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @admin_category }
      else
        format.html { render :new }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1
  # PATCH/PUT /admin/categories/1.json
  def update
    respond_to do |format|
      if @admin_category.update(admin_category_params)
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_category }
      else
        format.html { render :edit }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    @admin_category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def activate
    @admin_category = Category.find(params[:category_id])
    @admin_category.update_attribute(:status, !@admin_category.status)
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_category
      @admin_category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_category_params
      params.require(:category).permit(:name, :description, :position, :status, :image,:preview)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= simple_form_for([:admin, @admin_category],validate: true) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image,as: :file,:input_html => { :class => 'form-control' } %>
    <% if @admin_category.image.attached?%>
    <%= image_tag @admin_category.image.variant(resize: "100x100") %>
    <%= f.input :preview, :as => :hidden, :input_html => { :value => 1  }%>
    <%end%>
    <%= f.input :position %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,:class => "btn btn-success" %>
    <%= link_to 'Back', admin_categories_path , :class => "btn btn-info", data: { turbolinks: false } %>
  </div>
  <br>
<% end %>

app/views/admin/categories/edit.html.erb
<h3>Editing Category</h3>

<%= render 'form', admin_category: @admin_category %>

app/views/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="form-actions">
  <%= link_to 'Back', request.referer , :class => "btn btn-info custom-btn", data: { turbolinks: false } %>
  <%= link_to 'New Category', new_admin_category_path , :class => "btn btn-success custom-btn", data: { turbolinks: false } %>
</div>

<table class="table table-stripped table-hover" id="categories-table" data-source='<%= admin_categories_path(format: :json)%>' width="100%" >
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Status</th>
      <th>Actions</th/>
    </tr>
  </thead>
  <tbody>
  
  </tbody>
</table>

<br>

app/views/admin/categories/new.html.erb
<h3>New  Category</h3>

<%= render 'form', admin_category: @admin_category %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_category.description %>
</p>

<p>
  <strong>Position:</strong>
  <%= @admin_category.position %>
</p>

<p>
  <strong>Status:</strong>
  <%= @admin_category.status %>
</p>

<%= link_to 'Edit', edit_admin_category_path(@admin_category), data: { turbolinks: false } %> |
<%= link_to 'Back', admin_categories_path %>