config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  namespace :admin,:path => "cms" do
    root 'base#index'
    resources :top_brands
    match 'top_brands/set_order' => 'top_brands#set_order', via: [:post]
    resources :categories do
      match 'activate' => 'categories#activate', via: [:get]
    end
    resources :stores do
      match 'activate' => 'stores#activate', via: [:get]
    end
    resources :coupons do
      match 'activate' => 'coupons#activate', via: [:get]
    end
    resources :users do
      match 'activate' => 'users#activate', via: [:get]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/coupon.rb
class Coupon < ApplicationRecord
    belongs_to :store
    validates_presence_of :name,:description,:code,:url
    validates_uniqueness_of :name,:code
    validates_format_of :url, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix, :multiline => true
end

app/controllers/admin/coupons_controller.rb
class Admin::CouponsController < Admin::BaseController
  before_action :set_admin_coupon, only: [:show, :edit, :update, :destroy]

  # GET /admin/coupons
  # GET /admin/coupons.json
  def index
    # @admin_coupons = Coupon.all
    
    respond_to do |format|
      format.html
      format.json { render json: CouponDatatable.new(params,  view_context: view_context) }
    end

  end

  # GET /admin/coupons/1
  # GET /admin/coupons/1.json
  def show
  end

  # GET /admin/coupons/new
  def new
    @admin_coupon = Coupon.new
  end

  # GET /admin/coupons/1/edit
  def edit
  end

  # POST /admin/coupons
  # POST /admin/coupons.json
  def create
    @admin_coupon = Coupon.new(admin_coupon_params)

    respond_to do |format|
      if @admin_coupon.save
        #  @admin_coupon.image.attach(params[:image])
        format.html { redirect_to admin_coupons_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @admin_coupon }
      else
        format.html { render :new }
        format.json { render json: @admin_coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/coupons/1
  # PATCH/PUT /admin/coupons/1.json
  def update
    respond_to do |format|
      if @admin_coupon.update(admin_coupon_params)
        format.html { redirect_to admin_coupons_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_coupon }
      else
        format.html { render :edit }
        format.json { render json: @admin_coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/coupons/1
  # DELETE /admin/coupons/1.json
  def destroy
    @admin_coupon.destroy
    respond_to do |format|
      format.html { redirect_to admin_coupons_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def activate
    @admin_coupon = Coupon.find(params[:coupon_id])
    @admin_coupon.update_attribute(:status, !@admin_coupon.status)
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_coupon
      @admin_coupon = Coupon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_coupon_params
      params.require(:coupon).permit(:name, :description, :code, :status, :url,:store_id)
    end
end

app/helpers/admin/coupons_helper.rb
module Admin::CouponsHelper
end

app/views/admin/coupons/_form.html.erb
<%= simple_form_for([:admin, @admin_coupon],validate: true) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :store, as: :select,:input_html => { :class => 'select2' }%>
    <%= f.input :name %>
    <%= f.input :code %>
    <%= f.input :description %>  
    <%= f.input :url %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,:class => "btn btn-success" %>
    <%= link_to 'Back', admin_coupons_path , :class => "btn btn-info", data: { turbolinks: false } %>
  </div>
  <br>
<% end %>

app/views/admin/coupons/edit.html.erb
<h3>Editing Coupon</h3>

<%= render 'form', admin_coupon: @admin_coupon %>

app/views/admin/coupons/index.html.erb
<p id="notice"><%= notice %></p>

<div class="form-actions">
  <%= link_to 'Back', request.referer , :class => "btn btn-info custom-btn", data: { turbolinks: false } %>
  <%= link_to 'New Coupon', new_admin_coupon_path , :class => "btn btn-success custom-btn", data: { turbolinks: false } %>
</div>

<table class="table table-stripped table-hover" id="coupons-table" data-source='<%= admin_coupons_path(format: :json)%>' width="100%" >
  <thead>
    <tr>
      <th>ID</th>
      <th>Store</th>
      <th>Name</th>
      <th>Status</th>
      <th>Actions</th/>
    </tr>
  </thead>
  <tbody>
  
  </tbody>
</table>

<br>

app/views/admin/coupons/new.html.erb
<h3>New  Coupon</h3>

<%= render 'form', admin_coupon: @admin_coupon %>

app/views/admin/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_coupon.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_coupon.description %>
</p>

<p>
  <strong>Position:</strong>
  <%= @admin_coupon.position %>
</p>

<p>
  <strong>Status:</strong>
  <%= @admin_coupon.status %>
</p>

<%= link_to 'Edit', edit_admin_coupon_path(@admin_coupon), data: { turbolinks: false } %> |
<%= link_to 'Back', admin_coupons_path %>